name: my-first-github-workflow
run-name: {{ github.sha }}
on: 
 push:
  branches: ["main"]
 pull_request:
  brances:
    - main
 workflow_dispatch:

jobs:
 install-prerequistes:
   runs-on: ubuntu-latest
   steps:
     - name: install terraform
       run: |
         wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

