name: my-first-github-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
 push:
  branches: ["master"]
 pull_request:
  types: [opened,reopened]
 workflow_dispatch:
jobs:
 Deployment-Stage:
    uses: Prakashja/workflow-templates/.github/workflows/reusable-workflow.yaml@main
    with:
      docker_url: https//docker.io


