name: my-first-workflow

run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  workflow_dispatch:

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
    - name: install_pylint
      run: |
        sudo apt-get install python3-pip -y
        sudo pip install pylint
    - name: Checkout code
      uses: actions/checkout@v2
    - name: lint
      run: |
        pylint .
  run_unit_test:
    needs: run_lint
    runs-on: arc-gridos-devops-ci-cd-workout-runners
    steps:
      - name: install_pytest
        run: |
          sudo apt-get install python3-pip -y
          sudo pip install -U pytest    
      - name: unit-test
        run: |
          pytest .    
