name: my-first-workflow

run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  workflow_dispatch:

jobs:
  install-pre-requisites:
    runs-on: ubuntu-latest
    steps:
    - name: python
      run: |
        echo `cat /etc/os-release`
        python --version
        sudo apt-get install python3-pip -y
        sudo pip install pylint
        sudo pip install -U pytest
    - name: Checkout code
      uses: actions/checkout@v2
    - name: lint
      run: |
        pylint .
    - name: unit-test
      run: |
        pytest .
