name: my-first-workflow

run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
    - name: install_pylint
      run: |
        sudo apt-get install python3-pip -y
        sudo pip install pylint
    - name: Checkout code
      uses: actions/checkout@v2
    - name: lint
      run: |
        pylint .
  run_unit_test:
    needs: run_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install_pytest
        run: |
          sudo apt-get install python3-pip -y
          sudo pip install -U pytest
      - name: unit-test
        run: |
          pytest .
  run_aqua_test:
    needs: run_lint
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install_pytest
        run: |
         echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
         echo "Aqua test are passed successfully ....."
        env:
          First_Name: John
  run_docker_build:
    needs: run_unit_test
    runs-on: ubuntu-latest    
    environment: production
    steps:    
      - name: Checkout code
        uses: actions/checkout@v2
      - name: docker_run
        run: |
          echo "Docker Build ... {{ var.PROD_DOCKER_URI }}"
        if: gtihub.ref == 'refs/heads/master'  
